### ISSUE TITLE
Trigger `Actions` not copied when using `StyleBindings.Triggers`

### ISSUE THREAD

**Issue by Nintynuts** [tom-englert/TomsToolbox#17]
This is an [issue with the WPF behaviours project](https://github.com/microsoft/XamlBehaviorsWpf/issues/146) rather than this attached property, but it can be (at least partially) fixed by iterating over the source `Actions` and cloning them into the copy. If you do it conditionally based on whether the clone matches then it won't break if the underlying issue gets fixed.

```csharp
existingTriggers.AddRange(newValue.Select(item =>
{
	var triggerBase = (TriggerBase)item.Clone();
	if (item.Actions.Count > triggerBase.Actions.Count)
	{
		item.Actions.ForEach(a => triggerBase.Actions.Add((TriggerAction)a.Clone()));
	}
	return triggerBase;
}));
```

**Comment by tom-englert** [comment]
Can you provide a PR with the fix?

**Comment by Nintynuts** [comment]
Normally I'd be happy to, but my current job doesn't allow me to contribute to open source projects that way. I think I can get away with a code snippet you can apply yourself.

**Comment by tom-englert** [comment]
To be consequent, companies that don't allow to contribute to open source projects should also not allow to **use** open source.

**Comment by Nintynuts** [comment]
Thanks. I guess you will watch the issue I made on XamlBehaviorsWpf to know if the underling issue is fixed to remove yours. 

To be clear, I'm not allowed to contribute to anything in my own time without getting permission from my employer (which is painful/slow to request through legal).
