### ISSUE TITLE
Enhancement for BinaryOperationConverter

### ISSUE THREAD

**Issue by xaviergonz** [tom-englert/TomsToolbox#3]
Add new operations for >=, <=

On convert back do the opposite operation, this is:

```
+ to -
- to +
* to /
/ to *
== to !=
!= to ==
>= to <
<= to >
> to <=
< to >=
```

And maybe if the operation fails return UnsetValue so a FallbackValue can be used?

**Comment by tom-englert** [comment]
- Operations for >=, <= added
- returns UnsetValue on errors.

Convert back operation is not implemented, too few cases where it would really work...
