### ISSUE TITLE
Issues with converters when value is DependencyProperty.UnsetValue

### ISSUE THREAD

**Issue by xaviergonz** [tom-englert/TomsToolbox#4]
Basically the converters fail with a cast exception when the value is DependencyProperty.UnsetValue.

https://msdn.microsoft.com/en-us/library/system.windows.dependencyproperty.unsetvalue%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

Basically this value could be passed as value when you are binding for example to a binding that cannot be properly resolved at a certain point in time but that does get resolved in the future.
I had this problem with the VisibilityToBooleanConverter for example.

It can be easily solved by adding this as first line for all converters (or at least where it makes sense, which is usually most of them):

if (value == DependencyProperty.UnsetValue) 
return DependencyProperty.UnsetValue;

Also while at it, maybe add to VisibilityToBooleanConverter (and also to BooleanToVisibilityConverter) a property that lets you pick if a bool == false is Collapsed (default) or Hidden

And maybe for the sake of completeness add to each converter an attribute such as 

[ValueConversion(typeof(Visibility), typeof(bool))] 

Maybe the designer uses this info to know if the converter is proper for the type? but I'm not sure.

**Comment by tom-englert** [comment]
Good points. Maybe you want to contribute the changes?
