### ISSUE TITLE
Resharper error on ChessView.xaml

### ISSUE THREAD

**Issue by xaviergonz** [tom-englert/TomsToolbox#6]
Solution TomsToolbox.sln
    Project SampleApp
      SampleApp\Samples\ChessView.xaml:30 Cannot resolve symbol 'Loaded'

**Comment by tom-englert** [comment]
The XAML-Designer is sometimes really stupid - it often shows errors that are no errors, because it compiles and runs.

**Comment by xaviergonz** [comment]
Ok, I just thought that maybe you might want to supress the error.

**Comment by tom-englert** [comment]
The XAML-Designer is so bad, most of the time it's crashed, or at least generates false warnings, so I became (maybe too much) used to such errors. 
However in this case I found it can be improved by using the full "FrameworkElement.Loaded" notation. I'll fix this, thanks for pointing this out.
