### ISSUE TITLE
Add a NegateConverter

### ISSUE THREAD

**Issue by xaviergonz** [tom-englert/TomsToolbox#8]
A converter that will leave null/unset unchanged and that will:

Negate numbers (x = -x)
Negate bools (x = !x)

Additionally maybe:
Negate thickness (1,2,3,4 = -1,-2,-3,-4)

Alternatively do a UnaryOperationConverter that includes negate as an operation.

**Comment by tom-englert** [comment]
V 1.0.34: Added `UnaryOperationConverter.Negate`

**Comment by xaviergonz** [comment]
Awesome, does it support negating thickness btw?

**Comment by tom-englert** [comment]
No, thickness does not have a negate operator; if you would really need such a feature you can use the ThicknessMultiplyConverter with -1 as parameter.
